//! Embedded read-only web UI: Askama-templated HTML + htmx for auto-refresh, styled with
//! Tailwind CSS. No CDN, no runtime Node/npm/network dependency — the compiled Tailwind CSS
//! (`assets/tailwind.css`, generated by the standalone `tailwindcss` binary from
//! `assets/input.css`) and htmx (`assets/htmx.min.js`, vendored) are both baked into the
//! binary via `include_str!` and inlined directly into the single `GET /` response. Served at
//! `GET /` (full page) and `GET /ui/servers` (the htmx-polled table fragment) by `src/api.rs`.
//!
//! There is nothing to click: the daemon connects a server's tunnel on demand the moment a
//! client hits its port (see `manager.rs`), so this page is purely a live view of
//! `GET /api/servers` — server, port, load, and connection status — not a control panel.
//!
//! To regenerate the CSS after changing template classes: run the standalone `tailwindcss`
//! binary (<https://github.com/tailwindlabs/tailwindcss/releases>) —
//! `tailwindcss -i assets/input.css -o assets/tailwind.css --minify` — then rebuild.
use crate::manager::ServerStatus;
use askama::Template;

const TAILWIND_CSS: &str = include_str!("../assets/tailwind.css");
const HTMX_JS: &str = include_str!("../assets/htmx.min.js");

fn format_duration(secs: u64) -> String {
    let h = secs / 3600;
    let m = (secs % 3600) / 60;
    let s = secs % 60;
    if h > 0 {
        format!("{h}h {m}m {s}s")
    } else if m > 0 {
        format!("{m}m {s}s")
    } else {
        format!("{s}s")
    }
}

fn format_bytes(bytes: u64) -> String {
    const KIB: u64 = 1024;
    const MIB: u64 = 1024 * KIB;
    const GIB: u64 = 1024 * MIB;
    if bytes >= GIB {
        format!("{:.2} GiB", bytes as f64 / GIB as f64)
    } else if bytes >= MIB {
        format!("{:.2} MiB", bytes as f64 / MIB as f64)
    } else if bytes >= KIB {
        format!("{:.1} KiB", bytes as f64 / KIB as f64)
    } else {
        format!("{bytes} B")
    }
}

/// Display-oriented view of a [`ServerStatus`] with pre-formatted telemetry strings.
#[derive(Debug, Clone)]
pub struct ServerRow {
    pub name: String,
    pub country: String,
    pub country_code: String,
    pub city: Option<String>,
    pub port: u16,
    pub load: f64,
    pub connected: bool,
    pub open_connections: u32,
    pub uptime: String,
    pub handshake: String,
    pub sent: String,
    pub received: String,
}

/// Convert raw [`ServerStatus`]es into display [`ServerRow`]s, sorted by country then server
/// name so the table reads coherently rather than in whatever order `GET /api/servers` happens
/// to return.
pub fn server_rows(mut servers: Vec<ServerStatus>) -> Vec<ServerRow> {
    servers.sort_by(|a, b| {
        a.country_code
            .cmp(&b.country_code)
            .then_with(|| a.name.cmp(&b.name))
    });
    servers
        .into_iter()
        .map(|s| ServerRow {
            name: s.name,
            country: s.country,
            country_code: s.country_code,
            city: s.city,
            port: s.port,
            load: s.load.round(),
            connected: s.connected,
            open_connections: s.open_connections,
            uptime: s.uptime_secs.map(format_duration).unwrap_or_default(),
            handshake: s
                .handshake_age_secs
                .map(|secs| format!("{secs}s ago"))
                .unwrap_or_else(|| "—".to_string()),
            sent: format_bytes(s.bytes_sent),
            received: format_bytes(s.bytes_received),
        })
        .collect()
}

#[derive(Template)]
#[template(path = "index.html")]
pub struct IndexTemplate {
    pub tailwind_css: &'static str,
    pub htmx_js: &'static str,
    pub servers: Vec<ServerRow>,
}

impl IndexTemplate {
    pub fn new(servers: Vec<ServerStatus>) -> Self {
        Self {
            tailwind_css: TAILWIND_CSS,
            htmx_js: HTMX_JS,
            servers: server_rows(servers),
        }
    }
}

#[derive(Template)]
#[template(path = "servers.html")]
pub struct ServersTemplate {
    pub servers: Vec<ServerRow>,
}
