//! Embedded admin web UI: Askama-templated HTML + htmx for interactivity, styled with
//! Tailwind CSS. No CDN, no runtime Node/npm/network dependency — the compiled Tailwind CSS
//! (`assets/tailwind.css`, generated by the standalone `tailwindcss` binary from
//! `assets/input.css`) and htmx (`assets/htmx.min.js`, vendored) are both baked into the
//! binary via `include_str!` and inlined directly into the single `GET /` response. Served at
//! `GET /` (full page) and `GET /ui/*` (htmx fragment endpoints) by `src/api.rs`.
//!
//! To regenerate the CSS after changing template classes: run the standalone `tailwindcss`
//! binary (<https://github.com/tailwindlabs/tailwindcss/releases>) —
//! `tailwindcss -i assets/input.css -o assets/tailwind.css --minify` — then rebuild.
use crate::manager::{CountryInfo, ServerSummary, TunnelInfo};
use askama::Template;

/// Display-oriented view of a [`TunnelInfo`] with pre-formatted telemetry strings.
pub struct TunnelView {
    pub location: String,
    pub server: String,
    pub socks_port: u16,
    pub connected: bool,
    pub uptime: String,
    pub handshake: String,
    pub sent: String,
    pub received: String,
}

fn format_duration(secs: u64) -> String {
    let h = secs / 3600;
    let m = (secs % 3600) / 60;
    let s = secs % 60;
    if h > 0 {
        format!("{h}h {m}m {s}s")
    } else if m > 0 {
        format!("{m}m {s}s")
    } else {
        format!("{s}s")
    }
}

fn format_bytes(bytes: u64) -> String {
    const KIB: u64 = 1024;
    const MIB: u64 = 1024 * KIB;
    const GIB: u64 = 1024 * MIB;
    if bytes >= GIB {
        format!("{:.2} GiB", bytes as f64 / GIB as f64)
    } else if bytes >= MIB {
        format!("{:.2} MiB", bytes as f64 / MIB as f64)
    } else if bytes >= KIB {
        format!("{:.1} KiB", bytes as f64 / KIB as f64)
    } else {
        format!("{bytes} B")
    }
}

/// Convert raw [`TunnelInfo`]s into display [`TunnelView`]s with human-readable telemetry.
pub fn tunnel_views(tunnels: Vec<TunnelInfo>) -> Vec<TunnelView> {
    tunnels
        .into_iter()
        .map(|t| TunnelView {
            location: t.location,
            server: t.server,
            socks_port: t.socks_port,
            connected: t.connected,
            uptime: format_duration(t.uptime_secs),
            handshake: t
                .handshake_age_secs
                .map(|s| format!("{s}s ago"))
                .unwrap_or_else(|| "—".to_string()),
            sent: format_bytes(t.bytes_sent),
            received: format_bytes(t.bytes_received),
        })
        .collect()
}

const TAILWIND_CSS: &str = include_str!("../assets/tailwind.css");
const HTMX_JS: &str = include_str!("../assets/htmx.min.js");

/// A country row for the locations list, with `connected` filled in by `src/api.rs` from the
/// manager's (at most one) running tunnel — so the template can show "Connected" instead of an
/// actionable control once a location has a tunnel, rather than leaving a stale-looking button.
#[derive(Debug, Clone)]
pub struct LocationRow {
    pub code: String,
    pub name: String,
    pub load: f64,
    pub connected: bool,
}

/// Builds `LocationRow`s by matching each `CountryInfo` against the currently running tunnel
/// (if any). Shared by `index` and `ui_locations` in `src/api.rs`.
pub fn location_rows(locations: Vec<CountryInfo>, active: Option<&TunnelInfo>) -> Vec<LocationRow> {
    locations
        .into_iter()
        .map(|loc| {
            let connected = active.is_some_and(|a| a.location.eq_ignore_ascii_case(&loc.code));
            LocationRow {
                code: loc.code,
                name: loc.name,
                load: loc.load.round(),
                connected,
            }
        })
        .collect()
}

/// A server row for one country's expanded server list, with `connected` filled in by
/// `src/api.rs`: `true` only for the exact server the running tunnel (if any) is on.
#[derive(Debug, Clone)]
pub struct ServerRow {
    pub name: String,
    pub load: f64,
    pub connected: bool,
    pub location_connected: bool,
}

/// Builds `ServerRow`s for `location` by matching each `ServerSummary` against the currently
/// running tunnel (if any). Shared by `ui_location_servers` in `src/api.rs`.
pub fn server_rows(
    location: &str,
    servers: Vec<ServerSummary>,
    active: Option<&TunnelInfo>,
) -> Vec<ServerRow> {
    servers
        .into_iter()
        .map(|s| {
            let connected = active.is_some_and(|a| {
                a.location.eq_ignore_ascii_case(location) && a.server.eq_ignore_ascii_case(&s.name)
            });
            let location_connected = active.is_some_and(|a| a.location.eq_ignore_ascii_case(location));
            ServerRow {
                name: s.name,
                load: s.load.round(),
                connected,
                location_connected,
            }
        })
        .collect()
}

#[derive(Template)]
#[template(path = "index.html")]
pub struct IndexTemplate {
    pub tailwind_css: &'static str,
    pub htmx_js: &'static str,
    pub login_error: Option<String>,
    pub locations: Vec<LocationRow>,
    pub tunnels: Vec<TunnelInfo>,
    pub tunnel_views: Vec<TunnelView>,
}

impl IndexTemplate {
    pub fn new(
        login_error: Option<String>,
        locations: Vec<LocationRow>,
        tunnels: Vec<TunnelInfo>,
    ) -> Self {
        Self {
            tailwind_css: TAILWIND_CSS,
            htmx_js: HTMX_JS,
            login_error,
            locations,
            tunnels: tunnels.clone(),
            tunnel_views: tunnel_views(tunnels),
        }
    }
}

#[derive(Template)]
#[template(path = "locations.html")]
pub struct LocationsTemplate {
    pub locations: Vec<LocationRow>,
}

#[derive(Template)]
#[template(path = "tunnels.html")]
pub struct TunnelsTemplate {
    pub tunnel_views: Vec<TunnelView>,
}

#[derive(Template)]
#[template(path = "servers.html")]
pub struct ServersTemplate {
    pub location: String,
    pub servers: Vec<ServerRow>,
}

/// An out-of-band error banner (`templates/action_error.html`'s `#action-error` div), sent
/// alongside every start/stop action's response — see `render_tunnels_and_servers` in
/// `src/api.rs`. `None` renders an empty div, which clears (via `hx-swap-oob`'s default
/// outerHTML swap) whatever error was showing from a previous failed action.
#[derive(Template)]
#[template(path = "action_error.html")]
pub struct ActionErrorTemplate {
    pub error: Option<String>,
}
